In [9]:
import numpy as np
import pandas as pd

def simplex(r, v, c, a):
    df = pd.DataFrame(a)
    print(df.values)

In [11]:
r = 3
v = 3
c = [2,4,8]
a = [[1,0,0,1],[0,1,0,1],[0,0,1,1]]
simplex(r,v,c,a)

[[1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]]
